version: '3'

services:
  back:
    build:
      context: back
    ports:
      - "5146:5146"
    networks:
      - ems-net
    restart: always

  front:
    build:
      context: front
    ports:
      - "4200:4200"
    networks:
      - ems-net
    depends_on:
      - back
    restart: always

networks:
  ems-net:
    driver: bridge