version: '3'

services:
  back:
    build:
      context: back
    ports:
      - "5146:5146"
    networks:
      - ems-net

  front:
    build:
      context: front
    ports:
      - "4200:4200"
    networks:
      - ems-net

networks:
  ems-net:
    driver: bridge